import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
// import Navbar from "./components/navbar";
import MainMenu from "@/components/mainmenu";
import { Baloo_Bhai_2 } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const baloo = Baloo_Bhai_2({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-baloo",
});

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className bg-[#1e1e1e]`}>
        {/* <Navbar/> */}
        <MainMenu/>
        {children}
      </body>
    </html>
  );
}
